//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : IModule.h
//  @ Date : 2013/2/17
//  @ Author : 
//
//


#if !defined(_COMTOM_V3_SIPSERVICE_IMODULE_H_)
#define _COMTOM_V3_SIPSERVICE_IMODULE_H_


class IModule 
{
public:
    virtual void Init(const std::string& workPath) = 0;
    virtual void Start() = 0;
    virtual void Stop() = 0;
    inline const std::string& Name();

    static void DestroyModule(IModule*& pMod)
    {
        delete pMod;
        pMod = NULL;
    } 
protected:
    std::string m_ModName;
    IModule(const std::string& modName)
        :m_ModName(modName) {};
};

///////////////////////////////////////////////////
inline const std::string& IModule::Name() 
{
    return m_ModName;
}


#endif  //_COMTOM_V3_SIPSERVICE_IMODULE_H_
