//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : IMsgHandle.h
//  @ Date : 2013/2/17
//  @ Author : 
//
//


#if !defined(_COMTOM_V3_SIPSERVICE_IMSGHANDLE_H_)
#define _COMTOM_V3_SIPSERVICE_IMSGHANDLE_H_


class IMsgHandle 
{
public:
    virtual bool handleMsg() = 0;
};

#endif  //_COMTOM_V3_SIPSERVICE_IMSGHANDLE_H_
