//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : IUser.h
//  @ Date : 2013/2/17
//  @ Author : 
//
//


#if !defined(_IUSER_H)
#define _IUSER_H


class IUser {
};

#endif  //_IUSER_H
