//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : IVRUser.h
//  @ Date : 2013/2/17
//  @ Author : 
//
//


#if !defined(_IVRUSER_H)
#define _IVRUSER_H


class IVRUser {
};

#endif  //_IVRUSER_H
