//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : SIPService.cpp
//  @ Date : 2013/2/17
//  @ Author : 
//
//


#include "stdafx.h"
#include "SIPService.h"

SIPService::SIPService()
    :IModule("SIPService")
{

}


void SIPService::Init( const std::string& workPath )
{
    OUTPUT("Init sip service");
}

void SIPService::Start() 
{
    OUTPUT("Start sip service");
}

void SIPService::Stop() 
{
    OUTPUT("Stop Sip Service");
}

void* SIPService::threadFun(void* obj) 
{
    return 0;
}

void SIPService::lisent() {

}

