//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : UserMgr.cpp
//  @ Date : 2013/2/17
//  @ Author : 
//
//


#include "stdafx.h"
#include "UserMgr.h"

IUser* UserMgr::getUser() 
{
    return NULL;
}

