//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : User.h
//  @ Date : 2013/2/17
//  @ Author : 
//
//


#if !defined(_USER_H)
#define _USER_H

#include "IUser.h"

class User : public IUser {
};

#endif  //_USER_H
